default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  database: pikabu_api_development

test:
  <<: *default
  database: pikabu_api_test

production:
  <<: *default
  database: pikabu_api_production